# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Rique.Flashback
PackageVersion: 0.8.1
MinimumOSVersion: 10.0.22000.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
ProductCode: Flashback.Desktop
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- DisplayName: Flashback
  Publisher: Rique
  ProductCode: Flashback.Desktop
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Riqqqque/Flashback-Releases/releases/download/v0.8.1/Flashback-Setup-0.8.1.exe
  InstallerSha256: 0295211154E5EF10D033795E5D824E1BBDB2F96C5D46175E0EDE2A319171E2BD
ManifestType: installer
ManifestVersion: 1.12.0
